[workspace.package]
name = "hands_on_rust"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "BasicDungeonCrawler/dungeon_crawl_map",
    "BasicDungeonCrawler/dungeon_crawl_player",
    "first_game_flappy_dragon",
    "first_step_with_rust",
]
